### ISSUE TITLE
Enable docker-logs feature

### ISSUE THREAD

**Issue by jalberto** [Mashape/docker-kong#40]
As this image by default doesn't throw logs to std\* is harder to debug problems.

Nginx official docker use this trick to enalbe docker-logs:

```
# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log
```

**Comment by StephanZaat** [comment]
I would also like this feature. We actually cannot move to Kong 0.9.0 because the new Docker runs nginx as root user (which is good), but user nobody is not allowed to write to /dev/stdout.
In 0.8.3 we used the file-log plugin to log the output (instead of the method described by Jalberto).

This now gives the following error on each request in the nginx error log within the docker:
2016/08/28 16:01:18 [error] 76#0: [lua] handler.lua:56: [file-log] failed to open the file: Permission denied, context: ngx.timer, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:8000

**Comment by robermorales** [comment]
Any update on this?

**Comment by eric239** [comment]
Turning all logging to go to stdout is the recommended, and nowdays de-facto standard. Not having this supported by docker-kong makes it hard to deploy kong in a container environment... please, any word from the team?

**Comment by gaieges** [comment]
I would be happy to do this if you're okay with that @Tieske.  I could also use this on my end.

**Comment by GrantJamesPowell** [comment]
Did this get fixed? Its a bit of a blocker for us

**Comment by thibaultcha** [comment]
How about:

```
$ docker run --rm -d \
    --name kong --link kong-tests-postgres:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stdout" \
    -e "KONG_LOG_LEVEL=debug" \
    kong:0.11.0
```

**Comment by cilindrox** [comment]
@thibaultcha there's also the admin console and proxy access, eg:


      - KONG_ADMIN_ACCESS_LOG='/dev/stdout'
      - KONG_ADMIN_ERROR_LOG='/dev/stderr'
      - KONG_PROXY_ACCESS_LOG='/dev/stdout'
      - KONG_PROXY_ERROR_LOG='/dev/stderr'

**Comment by gaieges** [comment]
@cilindrox I couldn't get that to work previously, but somehow it's working now.  Thanks!
