### ISSUE TITLE
Graceful shutdown on docker stop

### ISSUE THREAD

**Issue by endeepak** [Mashape/docker-kong#92]
**Problem** 
Kong container doesn't remove its row from nodes table on stopping the container

**Steps to reproduce**
```
$ docker run -d -p 8000:8000 -p 8001:8001 -e KONG_DATABASE=postgres -e KONG_LOG_LEVEL=debug -e KONG_PG_HOST=<postgres_db_ip> kong:0.9.9
<container_id>
$ docker stop <container_id>
```

**Info**
Docker sends `SIGTERM` signal to the process on stopping a container. This signal should be trapped to stop kong gracefully

Reference : https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86

**Comment by Tigraine** [comment]
This is also a problem in production since connections get dropped when receiving `SIGTERM`

Kubernetes allows for a graceful shutdown by allowing each container a 30 sec window to shut down existing connections before the pod gets killed. Kong apparently shuts down immediately and terminates all connections along the way

**Comment by thefosk** [comment]
This problem doesn't exist in >= `0.11.x` because we changed the clustering invalidation mechanism, I would recommend to upgrade.
